### ISSUE TITLE
unintuitive metadata behaviour

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-python#164]
When you have a View object in `view` and you evaluate `'error' in view.metadata` then the result is true, but if you then access the `message` property you get an error (`KeyError: 'message'`).

**Comment by keighrim** [comment]
I can access the message by `a_view.metadata.error.message`.

**Comment by marcverhagen** [comment]
Ah, let me be clearer. The behaviour occurs when you check whether there is an error in a view that has no error so there is no message but  the value of `'error' in view.metadata` is True.

**Comment by keighrim** [comment]
Ah, I see. That definitely seems to be a bug. I'll fix in the next release.

**Comment by keighrim** [comment]
closed via #165.
