### ISSUE TITLE
Validation error on metadata with error property

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-python#171]
I am sending a file through a pipeline and intentionally create an error in step one and then try to run step two anyway, which gives a validation error.

The input file is

```json
{
  "metadata": { "mmif": "http://mmif.clams.ai/0.3.1"},
  "documents": [
    { "@type": "http://mmif.clams.ai/0.3.1/vocabulary/TextDocument",
      "properties": {
        "mime": "text",
        "location": "/data/text/east-tesseract.txt",
        "id": "d2" }}
  ],
    "views": []
}
```
And the output of the first step is

```json
{
  "metadata": {"mmif": "http://mmif.clams.ai/0.3.1"},
  "documents": [
    { "@type": "http://mmif.clams.ai/0.3.1/vocabulary/TextDocument", 
      "properties": {
        "mime": "text",
        "id": "d2",
        "location": "file:///data/text/east-tesseract.txt"}}
  ], 
  "views": [
    { "id": "v_0",
      "metadata": {
        "parameter": {"error": "dingdong", "pretty": true},
        "timestamp": "2021-05-26T20:29:21.408740",
        "app": "https://apps.clams.ai/spacy_nlp",
        "error": {
          "message": "<class 'Exception'>: spaCy error - dingdong",
          "stackTrace": "..."}},
      "annotations": []}
    ]
}
```

Note that I set up the app so that it will throw an error when it receives an error paramter.

The error I get

```
Failed validating 'required' in schema['properties']['views']['items']['properties']['metadata']:
    {'properties': {'app': {'format': 'uri', 'type': 'string'},
                    'contains': {'additionalProperties': False,
                                 'patternProperties': {'^https?://': {'$ref': '#/definitions/strStrMap'}},
                                 'type': 'object'},
                    'parameters': {'$ref': '#/definitions/strStrMap'},
                    'timestamp': {'format': 'date-time', 'type': 'string'}},
     'required': ['app', 'contains'],
     'type': 'object'}
```

What I don't get is that the above is not the schema for 0.3.1.

**Comment by keighrim** [comment]
Maybe the clams-python the app is based on is not using 0.3.1 spec. Can you see what value `mmif.__specver__` returns inside the app?

**Comment by marcverhagen** [comment]
Yeah, I checked that, both apps in the pipeline have mmif 0.3.1 and clams-python 0.2.4 in their metadata. And when I set up the requirements from the pipeline I use clams-python==0.2.4.

```python
>>> import mmif
>>> mmif.__specver__
'0.3.1'
```

**Comment by keighrim** [comment]
I tested the same mmif string with mmif-python 0.3.3 (__specver__ = 0.3.1) and couldn't reproduce the validation error. This is very weird... What do you get from the following? 

``` python 
>>> import json, pkg_resources, mmif
>>> sch = json.load(pkg_resources.resource_stream(f'{mmif.__name__}.{mmif._res_pkg}', mmif._schema_res_name))
>>> print(json.dump(sch, indent=2))
...
    "viewMetadata": {
      "type": "object",
      ...
      "oneOf": [
        {
          "required": [
            "app",
            "contains"
          ]
        },
        {
          "required": [
            "app",
            "error"
          ]
        }
      ]
    },
...

```

**Comment by marcverhagen** [comment]
I think I found the problem and it was caused purely by my own stupidity.

**Comment by marcverhagen** [comment]
By the way, the above code (with dumps instead of dump) gave me what looks like the 0.3.0 specs, which is also what the follow up app was using. I did the __specver__ part again and now it gave me 0.3.0 so I must have goofed the first time around.

This points at a tiny weakness in our process, which is that we specify versions in more than one spot (metadata and requirements) and that leaves room for errors that people like me will accidentally explore once in a while.
