### ISSUE TITLE
Accessing properties

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-python#186]
It would be nice to be able to access the annotation properties as if they are a dictionary. The simplest way that I have found is to serialize the properties and then do a json read. But at some point I had good use for a method to get all attribute names and for that I had to use the `_unnamed_attributes` variable and the `_named_attributes()` method, using something like the following:

```python
def get_attributes(annotation_properties: AnnotationProperties):
    attributes = []
    if hasattr(annotation_properties, '_unnamed_attributes') \
       and annotation_properties._unnamed_attributes is not None:
        attributes.extend(annotation_properties._unnamed_attributes)
    for name in annotation_properties._named_attributes():
        attributes.append(name)
    return attributes
```

which did not strike me as very elegant.

**Comment by keighrim** [comment]
A quick and (maybe not so) easy fix would be making `properties` object more like a `dict`, to have `keys()` and `items()` methods.

**Comment by keighrim** [comment]
#194 implements `AnnotationProperties` as a dict-like class, and future `AnnotationPropereis` (as well as `DocumentProperties`) will support `items()` and `keys()`.
