### ISSUE TITLE
Simplify codebase by removing freezing

### ISSUE THREAD

**Issue by eholderness95** [clamsproject/mmif-python#192]
Forcing freezability is not practical in Python, and since the CLAMS API does not allow mutability of MMIF objects that is enough security on its own.

**Comment by keighrim** [comment]
@marcverhagen also once mentioned the complexity of "reserved" attributes in the base `MmifObject`, and how that makes it hard to access properties in terminal `annotation` objects in an MMIF file. Should we also discuss the issue here, or do you want to start a new issue on it, @marcverhagen ?

**Comment by keighrim** [comment]
Actually, #186 seems to be related to the issue Marc mentioned. Then, I think #193 addresses all the issues here. Further discussion related to the other source of complexity (both in the code itself and property-accessing) can be continued in #186.

**Comment by keighrim** [comment]
Yup, I forgot to close this.
