### ISSUE TITLE
Document.get_property

### ISSUE THREAD

**Issue by snewman-aa** [clamsproject/mmif-python#231]
### Bug Description

When I try to access document location with `Document.get_property("location")` I get the error `Property location does not exist in this annotation`

Also `Mmif.get_views_for_document(Document.get_property("id"))` returns an empty list

### Reproduction steps

```
video_doc: Document = mmif.get_documents_by_type(DocumentTypes.VideoDocument)[0]
input_view: View = mmif.get_views_for_document(video_doc.get_property("id"))[0]
```
will lead to error `list index out of range`
`print(video_doc.get_property("location")`
will throw `Property location does not exist in this annotation`

### Expected behavior

It should return the specified property of the Document

`video_doc.get_property("id")` should return the id of the video document

### Additional context

properties are accessible via `video_doc.properties.id` and `video_doc.properties.location`

**Comment by keighrim** [comment]
#232 will fix this problem. HOWEVER for `location`, what you want is probably [`document.location_path()`](https://clams.ai/mmif-python/latest/autodoc/mmif.serialize.html#mmif.serialize.annotation.Document.location_path) that parses the location URI and gives you a local file path only.
