### ISSUE TITLE
Video Document Helper - new units

### ISSUE THREAD

**Issue by snewman-aa** [clamsproject/mmif-python#251]
### Because

The [video_document_helper](https://github.com/clamsproject/mmif-python/blob/develop/mmif/utils/video_document_helper.py) is outdated.

I don't think we should need unit conversion if we're sticking to using `milliseconds` for everything. In the same vein, should we update the helper to specifically work with `TimeFrame` and `TimePoint` annotations? I want to stick to using the `vdh` for the CV frame sampling/extraction tasks but it feels silly to bend the current methods to the way we're extracting images from `TimeFrames` now.

**Comment by keighrim** [comment]
I don't think we need to throw away the time conversion code in the vdh for now. Also, although we decided to use milliseconds for future implementation, MMIF spec hasn't been updated accordingly, so technically it is still "legal" to use other time units. 

For helper functions in the module in question, can you share an example code in which you're using helper functions for image extraction from `TimeFrame` for now? I can image something like this won't be too much of "bending" .
``` python
from mmif.utils import vdh

# some MMIF load 
mmif = load()
vd = some_video_document_from_mmif
tf = a_timeframe_object_from_mmif

vdh.extract_frames_as_images(vd, vdh.sample_frames(*vdh.convert_timeframe(mmif, tf, 'f'), num_samples), True)
```

**Comment by keighrim** [comment]
https://github.com/clamsproject/mmif-python/pull/254 should help reduce the "bending". @snewman-aa any thoughts?

**Comment by keighrim** [comment]
closing as stale.
