### ISSUE TITLE
Simple dictionaries are not allowed in annotation properties

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-python#252]
### Because

In https://github.com/clamsproject/app-swt-detection/issues/62 we discussed using a simple dictionary with classification results. This is allowed by the schema and we felt it would be a decent thing to do.

However, the add_property() method of the Mmif Annotation object does not allow this:

https://github.com/clamsproject/mmif-python/blob/887c30373a0bc658c19061d4735e9006c349a91b/mmif/serialize/annotation.py#L119-L124

We should decide whether this was a good idea, my vote would be to update `check_prop_value_is_simple_enough` and allow dictionary with atomic values.

**Comment by keighrim** [comment]
reopening this as test fails in #255 .

**Comment by keighrim** [comment]
As discussed in https://github.com/clamsproject/mmif/issues/215, current specification puts no restriction on data types (or format) in the annotation property. Hence adding any type checking/constraints in the SDK seems to be outside of SDK's responsibility or authority, if any. 787ca848ad7c87421b5513d910d14439358ade0f lifts the existing constrains off.
